### ISSUE TITLE
User Story: Employer can manage job postings.

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#82]
As an employer, I want to edit and delete my job postings.

4 story points: 1 for editing implementation, 2 for rest-api, 1 for delete job postings implementation.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can Create Job Postings|
| Quick Description  | The employer must be able to create new job postings so that candidates can apply to their company|
| Prerequisite  | Employer is signed up<br>Employer is logged on |
| Input | Click on "My Jobs" tab of the Employer page<br>Click on "Add Job"<br>Enter title, description, and deadline<br>Click "Save Job"|
| Expected Output | The job posting was added with the information entered and displayed in the list of job postings|
| Observed Output | The job posting was added with the information entered and displayed in the list of job postings|
| Verdict| Passed |
| Comments |  |

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can Edit Job Postings|
| Quick Description  | The employer must be able to edit existing job postings|
| Prerequisite  | Employer is signed up<br>Employer is logged on<br>There is an existing job posting |
| Input | Click on "My Jobs" tab of the Employer page<br>Click on the job title of the posting to be edited<br>Enter new information in the desired field<br>Click "Save Edits"|
| Expected Output | The job posting was updated with the information entered and displayed in the list of job postings |
| Observed Output | The job posting was updated with the information entered and displayed in the list of job postings|
| Verdict| Passed |
| Comments |  |

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can Delete Job Postings|
| Quick Description  | The employer must be able to delete existing job postings|
| Prerequisite  | Employer is signed up<br>Employer is logged on<br>There is an existing job posting |
| Input | Click on "My Jobs" tab of the Employer page<br>Click on the job title of the posting to be deleted<br>Click "Delete Job Post"|
| Expected Output | The job posting was deleted and removed from the list of job postings |
| Observed Output | The job posting was deleted and removed from the list of job postings |
| Verdict| Passed |
| Comments |  |
